### PR TITLE
feat: support custom path for extra media

### PR DESCRIPTION
**Pull request by sircharlo**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

-
-
-

Related to #2782

### CODE REVIEW

**Comment by sircharlo** [comment]
@mtdvlpr Would you care to try the folder watcher?
It's pretty rudimentary but honestly it works quite well in my limited testing.

**Comment by sircharlo** [comment]
Also: why are so many docs files in this PR, and how to i get rid of them lol

**Comment by sircharlo** [comment]
> Also: why are so many docs files in this PR, and how to i get rid of them lol

Alright, I cleaned up the bad merge I had done. This PR now actually contains the changes allowing for a watch folder!
Let me know what you think.

**Comment by mtdvlpr** [comment]
I'll have a look tomorrow :)

**Comment by mtdvlpr** [comment]
What happens with the `format` script is that prettier removes the escape characters from docs links and Crowdin adds them again. These two keep overwriting each other.

**Comment by mtdvlpr** [comment]
@sircharlo, could you take a look at https://github.com/sircharlo/meeting-media-manager/commit/a63f1e3119ff15ddda08ab61595ddc9f93ea47b7?

**Comment by sircharlo** [comment]
> @sircharlo, could you take a look at [a63f1e3](https://github.com/sircharlo/meeting-media-manager/commit/a63f1e3119ff15ddda08ab61595ddc9f93ea47b7)?

I will, tomorrow!

**Comment by mtdvlpr** [comment]
@sircharlo, nice work! I've added support for svg, heic and single-page pdfs. I tried to fix the long path overflowing the button with ellipsis, but I lost the padding between the icon and the label.

**Comment by sircharlo** [comment]
> @sircharlo, nice work! I've added support for svg, heic and single-page pdfs. I tried to fix the long path overflowing the button with ellipsis, but I lost the padding between the icon and the label. Should we also add support for multi-page pdfs?

Just out of curiosity, how are you handling file conversions like PDF, SVG, etc? Are you adding them into the monitored folders? I was thinking that the app should never write to the monitored folders, only read, but maybe I'm being too careful.

**Comment by mtdvlpr** [comment]
Good point. It's currently added to the watched folder indeed. This could give permission errors when it's a cloud controlled folder.

**Comment by sircharlo** [comment]
> Good point. It's currently added to the watched folder indeed. This could give permission errors when it's a cloud controlled folder.

I think I kind of want to leave it read-only; the users would be responsible for making sure that the files they need are already in a supported audio, image or video format.

**Comment by sircharlo** [comment]
LGTM!

**Pull request merged**
