### PR TITLE
feat: add option for fallback language

### PR DESCRIPTION
**Pull request by mtdvlpr**
Related to #816

@sircharlo, since this is quite a big modification to a big part of media fetching logic, I want two sets of eyes looking over it👀

TODO: 

- [x] use media fallback language as yeartext fallback
- [x] use availability check to prevent failing api calls for mwb and w pubs

### CODE REVIEW

**Comment by sircharlo** [comment]
For sure; I like the idea of this feature. I guess the way such a feature should work is:

    Fetch mwb in primary language
    IF SUCCESS: 
        Fetch media as per usual (using language as defined in mwb)
    IF FAIL:
        Fetch mwb in fallback language
        Fetch media in **primary** language 
            IF FAIL: Fetch media as per usual (using language as defined in mwb)

And the same for the w...

**Comment by mtdvlpr** [comment]
That is almost how I've implemented it! I don't know if the mwb is of the primary language, so I always try to fetch media using the primary language and if that fails the specified language in mwb or if that is the same as the primary language, the fallback language.

**Comment by sircharlo** [comment]
> That is almost how I've implemented it! I don't know if the publication is of the primary language, so I always try to fetch media using the primary language (when fallback lang is specified) and if that fails the specified language in the publication or if that is the same as the primary language, the fallback language.

Excellent, that seems like airtight logic. Will need to be tested with a few scenarios, of course, but the logic is good.

**Comment by mtdvlpr** [comment]
> Excellent, that seems like airtight logic. Will need to be tested with a few scenarios, of course, but the logic is good.

Yeah, the different sets of scenarios (I think) are:
- [ ] Available primary language without fallback (e.g. English): should function the same
- [ ] Available primary language with fallback (e.g. English with Dutch): should **NOT** fetch anything for the fallback language
- [ ] Unavailable primary language without fallback (e.g. Irish): should function the same
- [ ] Unavailable primary language with fallback (e.g. Irish with English): Should use primary language whenever possible
- [ ] Semi-available primary language without fallback (e.g. Abui): should function the same (use fallback specified in mwb)
- [ ] Semi-available primary language with fallback (e.g. Abui with English): use fallback specified in mwb over custom fallback

**Comment by sircharlo** [comment]
I came across an error with a clean media cache, ABU as main and E as fallback: 

image

**Comment by mtdvlpr** [comment]
Ah, I missed it because I still had English publication cache. The fallback language cache should also be removed when clearing cache

**Comment by sircharlo** [comment]
Also, ABU as main with no fallback gives errors fetching songs, even though the songs exist online:

image

**Comment by sircharlo** [comment]
> I noticed a mistake when trying to fetch the Abui media without a fallback. The video 'Jehovah Remembers Our Hard Work' was fetched for ABU, which failed. JW.org fetches the video in the fallback language IN. However, I could not find a way to extract the language of this video from the jwpub db, since it is not an Extract which has a Link attribute.

As for this, it might work on the website, but look at what happens in JW Library itself:

image

If JW Library itself doesn't do it, I don't see how we can. No doubt the website is using some other internal database, but JW Library uses JWPUB files, like we do. If they add the feature in JWPUB files to specify a language for the `Multimedia` table, then we can talk 😉

**Comment by sircharlo** [comment]
On a side note: look at this [article](https://wol.jw.org/abz/wol/d/r278/lp-abu/202022413). They forgot to make links into links? 😆

**Comment by mtdvlpr** [comment]
> > I noticed a mistake when trying to fetch the Abui media without a fallback. The video 'Jehovah Remembers Our Hard Work' was fetched for ABU, which failed. JW.org fetches the video in the fallback language IN. However, I could not find a way to extract the language of this video from the jwpub db, since it is not an Extract which has a Link attribute.
> 
> As for this, it might work on the website, but look at what happens in JW Library itself:
> 
> image
> 
> If JW Library itself doesn't do it, I don't see how we can. No doubt the website is using some other internal database, but JW Library uses JWPUB files, like we do. If they add the feature in JWPUB files to specify a language for the `Multimedia` table, then we can talk wink
> 
> No doubt an ABU congregation could simply use ABU as main language, and IN as fallback in the settings, to work around this current limitation of JWPUB files.

That's good to know :)

**Comment by mtdvlpr** [comment]
@sircharlo, the bugs you found should be resolved now. I made a mistake in the new language detection when using $pubPath(). It now tries mediaLang first, if that doesn't exist, lang specified in mwb and then fallback lang. It skipped straight to fallbackLang even if there is none previously

**Comment by sircharlo** [comment]
> @sircharlo, the bugs you found should be resolved now. I made a mistake in the new language detection when using $pubPath(). It now tries mediaLang first, if that doesn't exist, lang specified in mwb and then fallback lang. It skipped straight to fallbackLang even if there is none previously

They are, I was just testing it out. Works great for ABU (minus that one video), ABU/IN, and GC/E.

2 ideas: 

1. When the `mwb` and/or `w` is not available in a language, perhaps the notification could be modified to also say something about "perhaps consider setting a fallback language"?
2. Perhaps the JW tile could indicate the fallback language alongside the main language, when present? For example, right now it isn't clear that GC is configured along with W as a fallback:

image

**Comment by mtdvlpr** [comment]
Done and done :)

**Review by sircharlo — APPROVED** [review]
🎉 🎉 🎉

**Comment by mtdvlpr** [comment]
> No time like the present smile

Alight! Maybe give the translators a few days to update their translations for the fallback strings and then release a 12.1?

**Comment by sircharlo** [comment]
> > No time like the present smile
> 
> Alright! Maybe give the translators a few days to update their translations for the fallback strings and then release a 12.1? Some of them are very fast when it comes to new translation strings. Btw, will they receive a notification for the updated unavailable strings? Those were already translated by them, but should be changed now.

Good idea, and I don't think so. I'll check when this merges, but I don't recall ever being notified of new translations pending. I'd love it if GitLocalize had email notifications..!

**Comment by sircharlo** [comment]
Hey! It works, but no notification. So translators will have to check back manually.

image

**Pull request merged**
