### PR TITLE
chore: perform redirect every session

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

- 
- 
- 

Related to #[issue/discussion nr. here]

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, I accidentally remove the Crowdin GitHub integration alltogether instead of removing the docs branch...Sorry!

**Comment by mtdvlpr** [comment]
https://crowdin.com/project/meeting-media-manager/integrations/system/github

**Comment by sircharlo** [comment]
> @sircharlo, I accidentally removed the GitHub integration on Crowdin altogether instead of removing the docs branch...Sorry!

Haha no worries, I'll re-add it.

**Comment by sircharlo** [comment]
Alright, I think Crowdin is back in business

**Pull request merged**
