### PR TITLE
Feat/subtitles

### PR DESCRIPTION
**Pull request by mtdvlpr**

### CODE REVIEW

**Comment by sircharlo** [comment]
Oh wow. This is so good!

**Comment by mtdvlpr** [comment]
> Oh wow. This is so good!

Ready to be merged in your opinion? :)

**Review by sircharlo — CHANGES_REQUESTED** [review]
Could we add a checkbox/toggle button for the subtitles to the bottom of the media controller? Or to the individual video items themselves maybe? In the case where the user doesn't want the subtitles for some reason.

**Comment by mtdvlpr** [comment]
Good one!

**Review by sircharlo — APPROVED** [review]
Man this is awesome. 💯

**Pull request merged**
