### PR TITLE
feat: support jwlplaylist files

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

- 
- 
- 

Related to #2003

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, I've made a first setup for importing `.jwlplaylist` files. I tested it with a JWL video, JWL image, local video and local image and it seems to work correctly. I'll admit, it's not pretty. I'd love your feedback on it.

**Comment by sircharlo** [comment]
Very nice! Basic, but does what it needs to. I added a quick and dirty prefix to make sure the files are listed in the same order as in the jwlplaylist file.

**Comment by sircharlo** [comment]
Quick note: I tested with a playlist from my phone including a local picture taken with my camera in HEIC format. This didn't show, as we don't support HEIC as of yet. However, the same playlist file on JWL works great on Windows. It seems they convert HEIC on the fly or something. 

Should we look into adding HEIC support with something like https://github.com/catdad-experiments/heic-convert or https://github.com/alexcorvi/heic2any?

**Comment by mtdvlpr** [comment]
@sircharlo, we could do that, sure!

**Pull request merged**
