### PR TITLE
fix: correctly fetch wt songs for feb 2023 and later

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A different approach to get wt songs for wt issues February 2023 and later. I've checked for February and March and also checked if American Sign Language uses KeySymbol 'sjjm'.

Related to #1730

### CODE REVIEW

**Comment by sircharlo** [comment]
Oh wow, I hadn't noticed the change to the databases. Awesome.
I'm suggesting a change in the latest commit here, let me know what you think. 

My idea is, we only want images during the study, so the first query gets only images that are relevant.

The second query gets all videos that are in paragraphs that are also referenced in the DocumentExtract table (long story short, this will eliminate videos from footnotes - see 2023.04.30 for example).

What do you think?

**Comment by mtdvlpr** [comment]
@sircharlo, I think it's good to go now

**Comment by sircharlo** [comment]
Should the output folder be cleared as a migration step before this release? To get rid of the "bad" songs.

**Review by sircharlo — APPROVED** [review]

**Comment by mtdvlpr** [comment]
@sircharlo, all tests have run successfully (open their details to see), but there's some [issues with GitHub](https://www.githubstatus.com/). You could forcefully merge it if you want.

**Pull request merged**
