### PR TITLE
feat: add heic support

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

- 
- 
- 

Related to #2038

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, thoughts?

**Comment by sircharlo** [comment]
What is happening! 

        • skipped publishing  file=latest-linux.yml reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v23.6.1 version=23.6.1

---
I created it though:

image

**Comment by sircharlo** [comment]
Never mind, I'm stupid

**Comment by sircharlo** [comment]
Nope. Not working @mtdvlpr Something broke in the release pipeline

**Comment by sircharlo** [comment]
image

**Comment by mtdvlpr** [comment]
@sircharlo, you were missing a draft release with correct tag. V23.6.1 release should be underway now.

**Comment by sircharlo** [comment]
Ugh. I forgot the tag was important. Thanks

**Pull request merged**
