### PR TITLE
feat: make click again tooltips persistent

### PR DESCRIPTION
**Pull request by mtdvlpr**
@sircharlo, you also needed the disabled prop to prevent it from changing its state internally

Related to #892

### CODE REVIEW

**Comment by sircharlo** [comment]
> @sircharlo, you also needed the disabled prop to prevent it from changing its state internally
> 
> Related to #892

Wow, so simple. Is it just me or is that not in the [docs](https://vuetifyjs.com/en/components/tooltips/#visibility), or even in the example on the docs page?

**Review by sircharlo — CHANGES_REQUESTED** [review]
Looking good, except for the "clear cache" button tooltip

**Comment by mtdvlpr** [comment]
@sircharlo, I haven't found a way to fix this. Might I suggest combining the labels into one? `clear text (click again to confirm)`. The tooltip would still not show after clicking, but at least the click again text can be read beforehand.

**Comment by sircharlo** [comment]
> @sircharlo, I haven't found a way to fix this. Might I suggest combining the labels into one? `clear text (click again to confirm)`. The tooltip would still not show after clicking, but at least the click again text can be read beforehand.

And why is the same solution you used previously not working now (disabled + value)? I tried to do something along the lines of `:disabled="color !== warning" :value="color !== warning"`, but that didn't work naturally. I don't get why it works in other places but not here. Is it because the text of the tooltip is being replaced dynamically, therefore resetting some property somewhere?

**Comment by mtdvlpr** [comment]
It's because of the tooltip that's already there. I don't understand it fully, but the first tooltip is preventing the second tooltip from becoming active right after the click.

**Comment by mtdvlpr** [comment]
@sircharlo, I managed to improve the clear cache tooltip! It will now immediately show the click again tooltip when clicking on the button instead of having to move away from and back to the button. Haven't gotten the persistent working (yet), but after digging through the API docs I found some potential fixes.

**Comment by mtdvlpr** [comment]
@sircharlo, got it! I removed the activator on and attrs, which make the tooltip responsive to hover, focus and click. Doing that will also make the disabled prop unncessary, so I simplified all other persistent tooltips as well.

**Comment by sircharlo** [comment]
> @sircharlo, got it! I removed the activator on and attrs, which make the tooltip responsive to hover, focus and click. Doing that will also make the disabled prop unnecessary, so I simplified all other persistent tooltips as well.

Works great for me, at least visually! However the console throws this error now for the shuffle button, can that be ignored safely?

image

**Comment by mtdvlpr** [comment]
@sircharlo, fixed :)

**Review by sircharlo — APPROVED** [review]
Awesome sauce

**Pull request merged**
