### PR TITLE
fix: search

### PR DESCRIPTION
**Pull request by mtdvlpr**
Search was not working correctly. Now it is :)

### CODE REVIEW

**Comment by mtdvlpr** [comment]
Because of the protected branch rules you set, I require your approval before I can merge my changes :). You can turn off require approval if you feel like it's more of a hassle than a protection. Up to you.

**Comment by mtdvlpr** [comment]
You, as admin, have the option to force merge, without approval and passed checks

**Review by sircharlo — APPROVED** [review]

**Comment by sircharlo** [comment]
Can I turn off require approval just for you?

**Comment by mtdvlpr** [comment]
> Can I turn off require approval just for you?

GitHub says:
> The above settings will apply to administrators and custom roles with the "bypass branch protections" permission. 

So apparently you could give me a role with the "bypass branch protections" permission.

**Comment by sircharlo** [comment]
> You either turn it off or on for all collaborators. But since I'm the only collaborator (as of now), turning it off would only affect me.

Good point. I'll turn it off for now.

**Pull request merged**
