### PR TITLE
refactor: improve performance of download handling

### PR DESCRIPTION
**Pull request by sircharlo**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

-
-
-

Related to #[issue/discussion nr. here]

### CODE REVIEW

**Comment by sircharlo** [comment]
@mtdvlpr It's not perfect yet, but the download performance improvement is staggering.

**Comment by mtdvlpr** [comment]
This is awesome! 🚀

**Comment by sircharlo** [comment]
I added queueing to limit the number of active downloads to 5 and de-prioritize as needed. I feel this PR can be merged now. Do you agree? @mtdvlpr

**Comment by mtdvlpr** [comment]
@sircharlo, why'd you limit the number of parallel downloads? I think the browser will automatically see how many it can handle at once.

P.S. The initial migration stopped working. Not sure if it's this PR or a previous commit.

**Comment by sircharlo** [comment]
> @sircharlo, why'd you limit the number of parallel downloads? I think the browser will automatically see how many it can handle at once.

I found in my testing that (like Chrome) it would just add a million downloads and try to finish them all more or less at the same time. This is not desirable in the case of JWPUB files or background music for example; we want to add files gradually. The queue ensures that needed files are downloaded at higher speed and therefore available for use and processing faster.

> P.S. The initial migration stopped working. Not sure if it's this PR or a previous commit.

🤯

**Comment by sircharlo** [comment]
> @sircharlo, why'd you limit the number of parallel downloads? I think the browser will automatically see how many it can handle at once.
> 
> P.S. The initial migration stopped working. Not sure if it's this PR or a previous commit.

What part of the migration stopped working in your tests?

**Comment by mtdvlpr** [comment]
Well, I have my old folder with prefs, but when I clear the localStorage and restart, it just starts up with a fresh congregation instead of migrating my old prefs.

**Comment by sircharlo** [comment]
> Well, I have my old folder with prefs, but when I clear the localStorage and restart, it just starts up with a fresh congregation instead of migrating my old prefs.

And are you clearing both the Electron and the Meeting Media Manager folders?

**Comment by mtdvlpr** [comment]
No, just the localStorage and the cache through settings.

**Comment by sircharlo** [comment]
> No, just the localStorage and the cache through settings.

Ok, I'll take a look. FWIW I noticed that changes I make to localstorage are not persisted in dev if I ctrl-c to close the app, only if I close like a normal human using the X button.

**Comment by sircharlo** [comment]
Fixed! It was some async logic flaws 😄

**Review by mtdvlpr — APPROVED** [review]

**Comment by sircharlo** [comment]
Slating this for release with v24.11.1!

**Pull request merged**
