### PR TITLE
refactor: use JWPUB instead of JSON for study bible lookups

### PR DESCRIPTION
**Pull request by sircharlo**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

-
-
-

Related to #3481

### CODE REVIEW

**Comment by mtdvlpr** [comment]
Nice work so far! One thing I'm missing (maybe you already thought of it) is the English media when it's not available in the current media language. Do you (have a) plan to support that?

**Comment by sircharlo** [comment]
> Nice work so far! One thing I'm missing (maybe you already thought of it) is the English media when it's not available in the current media language. Do you (have a) plan to support that?

Yeah, I wanted to get everything working in English first as a base, then figure out the rest.

**Comment by sircharlo** [comment]
I think this is in good shape!
Thoughts?

**Review by mtdvlpr — APPROVED** [review]
Awesome! It would have taken me a lot longer to figure out the logic... 

I've added the fallback to English media, so that all study media is shown for every language.

**Comment by sircharlo** [comment]
Perfect! I'll merge it. 
Thanks!

**Pull request merged**
