### PR TITLE
feat: add co week picker

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

Adds a date picker to indicate the CO visit. For that week, the midweek meeting is set to Tuesday and the CBS media and last WT song are ignored. The date picker only allows Mondays and uses the app language when supported by Vuetify.

Related to #1247

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, had a chance to test this yet?

**Comment by sircharlo** [comment]
> @sircharlo, had a chance to test this yet?

Nope 😂 our new assignment means that spare time is an even rarer commodity than before, but I'll try to test it out this week!

**Comment by mtdvlpr** [comment]
> > @sircharlo, had a chance to test this yet?
> 
> Nope joy our new assignment means that spare time is an even rarer commodity than before, but I'll try to test it out this week!

No worries! Take your time :)

**Comment by sircharlo** [comment]
Works nicely! 
Two points.

On first run, the app complained of an invalid date:
image

Also, the MW concluding song was not skipped, even though it should.
image

**Comment by sircharlo** [comment]
Two more things I noticed.
___

If the date that is in the CO date field is not a Monday:
image
... then it is completely ignored:
image
Perhaps the date could be checked independently of whether it's a Monday or not?
___
Dates in the past are not wiped on app load:
image

**Comment by mtdvlpr** [comment]
@sircharlo, great points! You should only be able to select Mondays though. Did the date picker allow you to select other dates?

**Comment by sircharlo** [comment]
> @sircharlo, great points! You should only be able to select Mondays though. Did the date picker allow you to select other dates?

I sort of maybe definitely cheated. :)

**Comment by mtdvlpr** [comment]
@sircharlo, everything's fixed :)

**Comment by sircharlo** [comment]
> @sircharlo, thanks for the assist! Everything's fixed now :)

Awesome! What a great feature! Thanks for adding it!

**Review by sircharlo — APPROVED** [review]

**Pull request merged**
