### PR TITLE
fix: re-add missing files

### PR DESCRIPTION
**Pull request by mtdvlpr**
Restored missing files:

- `.gitattributes`: mostly to prevent corruption of image and font files
- GitHub issue, discussion and pull request templates
- GitHub stale action
- GitHub label action
- Auto merge Crowdin PRs (and squash them to keep the commit history clean)
- CHANGELOG, CODE_OF_CONDUCT, CONTRIBUTING, LICENSE and SECURITY
- Public folder of the documentation website

Changed `package.json` to logical order which aligns with [npm specs](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true)

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, the configured required checks do not match the new checks. Could you fix those settings so that PRs can pass inspection? :)

**Comment by mtdvlpr** [comment]
Also, you could add the url of the documentation website to the about section. There is a special `url` input for that reason.

**Comment by mtdvlpr** [comment]
I also added an automated way of showing the Crowdin progress on the README.md.

See: https://github.com/benjaminjonard/crowdin-translations-progress-action

To make this work, you'd need to add the following secrets to the repo:

```
CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

**Comment by sircharlo** [comment]
> @sircharlo, the configured required checks do not match the new checks. Could you fix those settings so that PRs can pass inspection? :)
> 
> I think the best configuration would be to not require any checks, but configure that all checks that are performed should succeed. Because the build checks are not (and should not be) performed when a PR only targets docs for example.

I'll give it a whirl.

**Comment by mtdvlpr** [comment]
Now I'm not allowed to create branches anymore because of 3 required rules...

**Comment by sircharlo** [comment]
> Now I'm not allowed to create branches anymore because of 3 required rules...

I'm not done 🤣

**Comment by mtdvlpr** [comment]
Sorry! Impatient me... 😅

**Comment by sircharlo** [comment]
Should be ok now I think!

**Pull request merged**
