### PR TITLE
feat: add option to receive beta releases

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

- 
- 
- 

Related to #1526

### CODE REVIEW

**Review by sircharlo — DISMISSED** [review]
Looks good, would it be good to add a note like "don't enable this option on the computer that is used to present media at meetings"?

**Comment by mtdvlpr** [comment]
@sircharlo, sure! I just have one thing I have to test with the automatic workflow. I think running it on a schedule is the way to go, instead of after every commit. Every half an hour? Every hour? What do you think?

**Comment by sircharlo** [comment]
> @sircharlo, sure! I just have one thing I have to test with the automatic workflow. I think running it on a schedule is the way to go, instead of after every commit. Every half an hour? Every hour? What do you think?

Once or twice a day is probably plenty, no? Will it publish a new beta release even when there are no commits since the last run? I'm just envisioning a scenario where a user is on beta-259 😆

**Comment by mtdvlpr** [comment]
> Once or twice a day is probably plenty, no? 

Fine by me!

> Will it publish a new beta release even when there are no commits since the last run?

That's what I'm still working on. There's an issue with checking the last commit message (if commit message is a release then there's nothing new).

**Comment by mtdvlpr** [comment]
@sircharlo, I have now added the workflow to automatically execute at 10am (10:00) and 10pm (22:00) UTC. Also, is the warning note good like this?

**Comment by mtdvlpr** [comment]
> perhaps the beta toggle should be hidden if auto updates are disabled?

I don't think so. When auto updates are disabled, you'll still get a notification when a new release is available with the option to install it right away. If you have auto updates disabled, you could still want to receive the beta releases

**Comment by mtdvlpr** [comment]
You can also execute this beta release workflow manually if you really want to release a new beta version. I also found a GitHub action to remove all old beta releases when a new stable version is released. Shall I add that here?

**Comment by sircharlo** [comment]
> > perhaps the beta toggle should be hidden if auto updates are disabled?
> 
> I don't think so. When auto updates are disabled, you'll still get a notification when a new release is available with the option to install it right away. If you have auto updates disabled, you could still want to receive the beta releases

Right on. I forgot that the user is still notified. My bad. (Does it show that I've never used that option? 😄)

**Comment by sircharlo** [comment]
> You can also execute this beta release workflow manually if you really want to release a new beta version. 

Very nice

> I also found a GitHub action to remove all old beta releases when a new stable version is released. Shall I add that here?

Definitely!

**Comment by mtdvlpr** [comment]
> I also found a GitHub action to remove all old beta releases when a new stable version is released. Shall I add that here?
> > Definitely!

Done :)

**Pull request merged**
