### PR TITLE
Fix/several

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

List of fixes

- Fixed video scrubbing slider
- Fixed notifications with the same key
- Fixed cache moved when opening settings
- Use WT font in yeartext preview
- Remove yeartext preview font-size due to broken scaling
- When disabling OBS integration, reset the current obs connection
- When opening presentation mode, check if obs is enabled AND if port and password are filled in

I tried to add the logo to the yeartext preview, but eventually I gave up and declared it too much hassle for what it's worth. Feel free to give it a go yourself :)

@sircharlo, I suggest releasing a 23.1.1 relatively soon (start of next week?) because of the lffi bug, obs bugs and the video scrubbing bug in particular.

Related to #1019, #997

### CODE REVIEW

**Comment by sircharlo** [comment]
Giving this one a whirl! 
Curious, why did you remove the font size? (`font-size: 1.35cqw;`)

On my setup, that resulted in an accurate depiction of the media window:
image

Without it, looks weird:
image

**Comment by mtdvlpr** [comment]
Try maximizing the window. The font gets too large.

**Comment by sircharlo** [comment]
How about now? I made the yeartext preview font size dependant on the parent container's size; and I added a sort of logo preview. Probably messy, but it's a first attempt :P

**Comment by mtdvlpr** [comment]
@sircharlo, awesome job! I couldn't get the positioning right. Made some tweaks to make it more like the actual yeartext and optimized the loading of the fonts

**Comment by sircharlo** [comment]
> @sircharlo, I suggest releasing a 23.1.1 relatively soon (start of next week?) because of the lffi bug, obs bugs and the video scrubbing bug in particular.

I agree!

**Comment by mtdvlpr** [comment]
@sircharlo, no more nitpicks? :)

**Comment by sircharlo** [comment]
Lol. Not on my side! Not for now, anyways 😆

**Comment by joaochris** [comment]
@mtdvlpr I noticed that in next week's media, print media is showing without the option checked. Is this a bug?

**Comment by mtdvlpr** [comment]
@joaochris, you're right! Turns out the printed image of the overview is a different category than the other printed images. I have added the missing category and fixed it in #1038

**Comment by sircharlo** [comment]
Are we ready for 23.1.1 ? @mtdvlpr

**Comment by mtdvlpr** [comment]
@sircharlo, I'd say so! Only thing might be if we want to wait for @mchaplyak. I accidentally removed his initial translation progress in my zeal to prepare...

**Comment by mchaplyak** [comment]
@mtdvlpr  i'm done

**Pull request merged**
