### PR TITLE
fix: ignore lff videos other then cbs

### PR DESCRIPTION
**Pull request by mtdvlpr**
@sircharlo, I suppose this does the trick. Ignore videos from Extract when another lff extract is present with a greater BeginParagraphOrdinal.

Related to #874

### CODE REVIEW

**Comment by sircharlo** [comment]
Would this cause issues for languages that don't study the `lff` book? Or for example in the future when the publication changes. Just thinking out loud. I tend to dislike any publication hardcoding whenever possible.
(I wish there was an clean way/API to fetch the appropriate songbook for each language lol)

**Comment by mtdvlpr** [comment]
> Would this cause issues for languages that don't study the `lff` book? Or for example in the future when the publication changes. Just thinking out loud. I tend to dislike any publication hardcoding whenever possible. (I wish there was an clean way/API to fetch the appropriate songbook for each language lol)

It only changes the logic if the extract is of pub lff and there's another extract of lff. Otherwise the normal logic for fetching is used.

**Comment by mtdvlpr** [comment]
I am wondering though. Weren't the exclude lffi images and exclude lffi videos toggles originally meant for this use case?

**Comment by sircharlo** [comment]
> @sircharlo, I suppose this does the trick. Ignore videos from Extract when another lff extract is present with a greater BeginParagraphOrdinal.

Would this logic be problematic in the (unlikely) case that there would be multiple extracts with the same BeginParagraphOrdinal? (Example, the CBS is based on paragraphs, and a chart found later in the same document. This is represented as two seperate lines in the Extract table.)

**Comment by sircharlo** [comment]
> I am wondering though. Weren't the exclude lffi images and exclude lffi videos toggles originally meant for this use case? Should we repurpose them to exclude the images / videos of the lff pub when used outside of cbs?

But to answer your question, I suppose that those toggles could indeed be repurposed. I believe that "exclude images from lffi" is no longer needed imo, and "exclude audio/video from lffi" could become something like "Include audio/video files from the Live Life Forever publications for the CBS only"

**Comment by mtdvlpr** [comment]
> Would this logic be problematic in the (unlikely) case that there would be multiple extracts with the same BeginParagraphOrdinal? (Example, the CBS is based on paragraphs, and a chart found later in the same document. This is represented as two seperate lines in the Extract table.)

No, because then there would not be a match with a greater BeginParagraphOrdinal, so the normal fetch logic would be used and everything would therefore be included

**Comment by mtdvlpr** [comment]
> But to answer your question, I suppose that those toggles could indeed be repurposed. I believe that "exclude images from lffi" is no longer needed imo, and "exclude audio/video from lffi" could become something like "Include audio/video files from the Live Life Forever publications for the CBS only"

Based on your other comment, I would say that the exclude images can be repurposed to exclude images from lff outside of cbs (same use case as before, just updated to lff because we are past the first 3 lessons) and the exclude videos can be removed (seeing as the videos are never to be played). Am I wrong?

**Comment by sircharlo** [comment]
I just haven't heard from anyone actually using the toggle to disable _images_ from the lffi brochure, seing as the images are relevant and often used by the students. I wonder if this toggle is necessary at all.
And since the videos won't be downloaded at all with this PR, then for sure, the "exclude audio/video files" toggle won't be necessary anymore, unless at some point the lessons from the brochure are used for the initial and second conversation demonstrations.

**Comment by mtdvlpr** [comment]
Our congregation never uses those images, so I would like the toggle for myself then :)

**Comment by mtdvlpr** [comment]
As for the videos, even for initial and return visits, the video always has the description: reference the video, but don't play it.

**Comment by mtdvlpr** [comment]
@sircharlo, that should do the trick :)

P.S. To make it work locally, you need to set the migration v23.1.0 to v22.0.0 and in your prefs.json you need to set the migrated version to before v21.0.0 because locally the Electron version is used (22.0.0) instead of the package.json version.

**Comment by mtdvlpr** [comment]
> unless at some point the lessons from the brochure are used for the initial and second conversation demonstrations.

I just read it correctly. For that use case, we could leave the lffi logic in, force the video filtering and use the image toggle for the brochure as well.

**Comment by sircharlo** [comment]
> @sircharlo, that should do the trick :)
> 
> P.S. To make the migration work locally, you need to set the migration v23.1.0 to v22.0.0 and in your prefs.json you need to set the migrated version to v21.0.0 because locally the Electron version is used (22.0.0) instead of the package.json version.

Looks awesome. Picture from student assignment shows when toggle is disabled, and vice versa.

**Review by sircharlo — APPROVED** [review]

**Pull request merged**
