### PR TITLE
feat: allow custom cache location

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A new setting `custom cache location` which would become the location where the Publications and Fonts folders are stored.

Related to #990

### CODE REVIEW

**Review by sircharlo — APPROVED** [review]
Nice feature! Works very well and will be super useful.

**Comment by sircharlo** [comment]
@mtdvlpr Think I found a bug with this. If I set a custom cache location, relaunch the app, and go to Settings, every time I get two warnings:

image
image

**Comment by mtdvlpr** [comment]
It' because the settings are loaded in, so the cache path goes from null to your path. Then it tries to move your cache from the default path to your "new" custom path. The problem is it can't be differentiated from a manual change. The error in the console is another matter. The identifier should be included in the message id.

**Comment by mtdvlpr** [comment]
@sircharlo, fixed in #1021

**Pull request merged**
