### PR TITLE
feat: auto start music option

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

Auto start shuffle music if the following requirements are met:

- Shuffle music is enabled and auto start option is enabled
- It's a meeting day
- The meeting starts in less than 1 hour
- The music would play for at least 1 minute after auto starting

Related to #1473

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, the one thing I am not sure about is the placement of this logic. It's currently in the shuffle button itself, meaning the logic is executed every time you land on the home screen or the presentation mode screen. I am picturing a scenario where you manually stop the music at the home screen before the meeting (for some reason) and then open the presentation mode only for the music to start up again.

**Comment by sircharlo** [comment]
> @sircharlo, the one thing I am not sure about is the placement of this logic. It's currently in the shuffle button itself, meaning the logic is executed every time you land on the home screen or the presentation mode screen. I am picturing a scenario where you manually stop the music at the home screen before the meeting (for some reason) and then open the presentation mode only for the music to start up again.

I was thinking that it would get triggered at the same time as the automatic sync (if enabled): on app startup.

**Comment by mtdvlpr** [comment]
@sircharlo, gotchu :)

**Review by sircharlo — APPROVED** [review]
Tested, works great!! I'm excited for this one 😄

**Pull request merged**
