### PR TITLE
fix: process refs of internal refs

### PR DESCRIPTION
**Pull request by mtdvlpr**

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, I think I managed to fix #744 here. Here I also process the internal references of the internal references. So the mwb jwpub file references the treasures part and the treasures part references another treasures part from another place. It will now also include the images of that sub reference. My only question is, does this always do what we want or will it sometimes get too much media? What do you think?

**Comment by sircharlo** [comment]
Hey, sorry I've been out of it. I'm slowly recovering from COVID. I'll try to test this branch against the next few weeks of media and see what the cat drags in, if it's too generous of a fetch. I seem to remember not wanting this behavior when I started investigating the fetch logic a few years back, but I can't remember why exactly.

**Comment by mtdvlpr** [comment]
Sorry to hear! Hope you're feeling better. Take your time. I will also test it further (although internal refs inside internal refs don't happen that often).

**Comment by mtdvlpr** [comment]
So, I tested all the upcoming weeks currently selectable. Everything is as expected.

**Comment by sircharlo** [comment]
Seems to works well! One minor glitch I noticed: now, the inline videos are attempted to be fetched and fail, since there is no JWPUB for them: 

image

Perhaps internal refs that have the `PublicationCategorySymbol` of `web` (from the `RefPublication` table) should be ignored? From what I can tell, that category doesn't have JWPUB files made available anyways.

**Comment by mtdvlpr** [comment]
Hmm, this also happens on the master branch, so it's unrelated to this new piece of code

**Comment by mtdvlpr** [comment]
So the Russian workbook refers to the videos used in the ministry using a non existing publication. I though it was just a mistake, but they're using it consistently so it must have a reason. I think we can indeed exclude web extracts to avoid these calls. I'll include it in this branch

**Comment by mtdvlpr** [comment]
If that's all, we can merge this now :)

**Comment by mtdvlpr** [comment]
Since this issue is also present in the upcoming midweek meeting (the same Ahab chart is referenced), we might consider releasing v22.12.0 early.

**Comment by sircharlo** [comment]
> Since this issue is also present in the upcoming midweek meeting (the same Ahab chart is referenced), we might consider releasing v22.12.0 early.

Definitely! Good detective work 🙂

**Comment by sircharlo** [comment]
Do you think 22.12.0 is ready for primetime?

**Comment by mtdvlpr** [comment]
> Do you think 22.12.0 is ready for primetime?

Yes! You can complete your translations and then we're good to go, I'd say :)

**Comment by sircharlo** [comment]
Done 😃

**Comment by mtdvlpr** [comment]
Then the honor is all yours ;)

**Pull request merged**
