### PR TITLE
feat: add headings to media list

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

Adds headers to the media list to quickly see what media belongs to which part of the meeting (treasures, apply, living, public talk, watchtower).

Related to #1376

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, here you go :)

I chose to store the Watchtower titles in the same location as the media for that date in the form of a file with a .title extension and the Workbook headings as a json file in the cache/lang/mwb folder. I used the colors that are used on jw.org to display the different Workbook headings. I also took this importunity to extract the media list from the MediaControls component and put it in its own component.

**Comment by sircharlo** [comment]
Really nice! I love the clean implementation. 
A bug I noticed (note the highlighted part is attributed to the wrong section, it's actually from the Gems, which falls under the Treasures):

image

**Comment by mtdvlpr** [comment]
@sircharlo, that makes it a whole lot trickier. The current logic to find the first Apply yourself item relies on the fact that it comes after the 02 prefix (which is the 10-min treasure media). Provided the excludeTh toggle is disabled we can use the bible reading th to improve its accuracy, but when that toggle is enabled, I don't have a quick solution for always finding the correct Apply yourself item...do you?

**Comment by sircharlo** [comment]
> @sircharlo, that makes it a whole lot trickier. The current logic to find the first Apply yourself item relies on the fact that it comes after the 02 prefix (which is the 10-min treasure media). Provided the excludeTh toggle is disabled we can use the bible reading th to improve its accuracy (need a way to discern its a th media file), but when that toggle is enabled, I don't have a quick solution for always finding the correct Apply yourself item...do you?

The BeginParagraphOrdinal for the Bible reading is always 10. For example:

image

image

So, in the MW media Map that's generated:
- anything that has a BeginParagraphOrdinal of 10 and under = Treasures
- BeginParagraphOrdinal of 11 to [whatever BeginParagraphOrdinal corresponds to the second song minus 1] = Apply
- BeginParagraphOrdinal of second song to the end: Living

**Comment by sircharlo** [comment]
Seems like the Living section is always BeginParagraphOrdinal 18 and up from the preliminary analysis I've done.

**Comment by mtdvlpr** [comment]
@sircharlo, I have improved the logic:
- If the media has been fetched in the same session (the meeting map exists) it's always correct (I found that the bible reading lesson has BeginParagraphOrdinal 12)
- If `excludeTh` is disabled, it's always correct (find the first item that matches `- {word} {number} - `)
- The fallback is only wrong in the case that the gems has media

**Comment by sircharlo** [comment]
> @sircharlo, I have improved the logic of finding the first Apply item:
> 
> * If the media has been fetched in the same session (the meeting map exists) it's always correct (first BeginParagraphOrdinal above bible reading)
> * If `excludeTh` is disabled, it's always correct (find the first item that matches `- {word} {number} - ` when skipping over the first song)
> * The fallback would only wrong in the case that the gems has media (which is seldom) or the treasures has no media (which is never?)
> 
> I found that the bible reading lesson has BeginParagraphOrdinal 12 (the textareas for answers have their own beginParagraphOrdinal)

Looks great from here!

**Comment by mtdvlpr** [comment]
@sircharlo, you think it's ready to be merged?

**Comment by sircharlo** [comment]
On app restart, the issue doesn't present itself, until I do a media sync. Perhaps I'm wrong, but I suspect it has to do with the missing media for that week.

**Comment by mtdvlpr** [comment]
@sircharlo, you're right! The missing media item is the first Apply item and when trying to find its index it returns -1.

**Comment by sircharlo** [comment]
Nice! Last thing: the media is now fine on initial app load, but if i run a media sync, it looks like the "missing" media is populated with the previous media file, resulting in a duplicate listing.

Before media sync:

image

After media sync for that week:

image

**Comment by sircharlo** [comment]
Before sync: 

```
[
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/01-01 - Song 123 - Loyally Submitting to Theocratic Order.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/02-01 - Brothers and sisters before a congregation meeting - 1 -  They greet and talk with one another - 2 -  A brother shows a sister something posted on the information board -.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/04-01 - Song 101 - Working Together in Unity.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/05-01 - Devastating Flooding in Brazil.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/05-02 - A scene from the video Devastating Flooding in Brazil -  An aerial view of partially submerged houses and trees in a flooded neighborhood.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-01 - An image of page 163 of the book.png",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-02 - Lesson 39 - A microscopic view of the bloodstream.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-03 - An image of pages 164-165 of the book.png",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-04 - How to Make Health-Care Decisions Regarding Blood.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-05 - Collage - A man making a medical decision - 1 -  He prays - 2 -  He does research using the Bible Bible-based publications and an electronic tablet - 3 -  He talks with h.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-06 - Interview of Professor Massimo P - Franchi M - D.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-07 - A test tube containing blood separated into its four main components which are labeled A B C and D.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-08 - An image of page 166 of the book.png",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-09 - Mark Sanderson - Jehovah Supports the Sick Acts 15 - 29.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/07-01 - Song 127 - The Sort of Person I Should Be.mp4"
]
```

After sync:

```
[
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/01-01 - Song 123 - Loyally Submitting to Theocratic Order.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/02-01 - Brothers and sisters before a congregation meeting - 1 -  They greet and talk with one another - 2 -  A brother shows a sister something posted on the information board -.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/02-01 - Brothers and sisters before a congregation meeting - 1 -  They greet and talk with one another - 2 -  A brother shows a sister something posted on the information board.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/04-01 - Song 101 - Working Together in Unity.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/05-01 - Devastating Flooding in Brazil.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/05-02 - A scene from the video Devastating Flooding in Brazil -  An aerial view of partially submerged houses and trees in a flooded neighborhood.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-01 - An image of page 163 of the book.png",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-02 - Lesson 39 - A microscopic view of the bloodstream.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-03 - An image of pages 164-165 of the book.png",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-04 - How to Make Health-Care Decisions Regarding Blood.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-05 - Collage - A man making a medical decision - 1 -  He prays - 2 -  He does research using the Bible Bible-based publications and an electronic tablet - 3 -  He talks with h.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-06 - Interview of Professor Massimo P - Franchi M - D.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-07 - A test tube containing blood separated into its four main components which are labeled A B C and D.jpg",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-08 - An image of page 166 of the book.png",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/06-09 - Mark Sanderson - Jehovah Supports the Sick Acts 15 - 29.mp4",
    "C:/Users/sirch/Videos/MMM/E/2023-03-09/07-01 - Song 127 - The Sort of Person I Should Be.mp4"
]
```

**Comment by sircharlo** [comment]
Note the extra dash... Some sort of sanitization issue?

Steps to replicate bug:

1. Delete media folders
2. Sync current week
3. Sync week of March 6
4. Test presentation mode: all as expected for week of March 6
5. Sync current week again
6. Sync week of March 6 again
7. Test presentation mode: duplicate entry for March 6

**Comment by mtdvlpr** [comment]
@sircharlo, still no on the reproduction...for me the safeNames is `02-01 - Brothers and sisters before a congregation meeting - 1 -  They greet and talk with one another - 2 -  A brother shows a sister something posted on the informat.jpg` all the time.

**Comment by sircharlo** [comment]
> "C:/Users/sirch/Videos/MMM/E/2023-03-09/

I think we've stumbled onto an edge case. Humor me.
Set your media path to something that's exactly 25 characters, like mine: `C:\Users\sirch\Videos\MMM`.
Test my repro steps again

**Comment by mtdvlpr** [comment]
@sircharlo, here we go! I did what you asked and did get a duplicate image. I only have one image locally without the dash and in the presentation screen I have two images with the same name (without the dash).

**Comment by mtdvlpr** [comment]
I think I know what's going on. So the first time, the full filename is sanitized from `02-01 - Brothers and sisters before a congregation meeting - 1 -  They greet and talk with one another - 2 -  A brother shows a sister something posted on the information board - 3 -  A sister places a donation in the contribution box - 4 -  A brother behind the counter hands literature to a sister - 5 -  A brother adjusts a microphone on the platform - 6 -  A brother and his young son clean.jpg` to `02-01 - Brothers and sisters before a congregation meeting - 1 -  They greet and talk with one another - 2 -  A brother shows a sister something posted on the information board -.jpg`. Then when opening presentation mode, all files get sanitized again to make sure locally added files are correctly added and then the file gets sanitized from `02-01 - Brothers and sisters before a congregation meeting - 1 -  They greet and talk with one another - 2 -  A brother shows a sister something posted on the information board -.jpg` to `02-01 - Brothers and sisters before a congregation meeting - 1 -  They greet and talk with one another - 2 -  A brother shows a sister something posted on the information board.jpg` which already exists

**Comment by mtdvlpr** [comment]
@sircharlo, I fixed it by always sanitizing filenames twice

**Comment by sircharlo** [comment]
Awesome! Ready for release in my estimation! I'm excited for this one

**Review by sircharlo — APPROVED** [review]

**Pull request merged**
