### PR TITLE
chore(release): v23.4.2

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

- 
- 
- 

Related to #[issue/discussion nr. here]

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, shall we release these fixes?

**Comment by sircharlo** [comment]
> @sircharlo, shall we release these fixes?

Sure! 

Did you get a chance to test clearing your cache on Windows to see if fetching felt slower now? I actually wondered if an update to axios or Electron had broken something when it comes to API or file fetching.

**Comment by mtdvlpr** [comment]
I'll test that right now!

**Comment by mtdvlpr** [comment]
@sircharlo, I'm noticing any difference in performance

**Comment by sircharlo** [comment]
> @sircharlo, I'm not noticing any difference in performance

Time to reinstall Windows for me. 😂

**Pull request merged**
