### PR TITLE
feat: add mouse indicator to jw.org in m3

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

Adds a red circle (can be anything) to indicate where the mouse is when presenting jw.org.

@sircharlo, ~it seems that Electron v23 breaks the present jw.org feature (I have to investigate further), so I reverted it to v22 here.~

Don't forget to run `yarn compile` when testing locally ;)

Related to #761

### CODE REVIEW

**Review by sircharlo — COMMENTED** [review]
Love it! The mouse pointer works very nicely in my tests. 
I noticed though a bug with the website mode in general: if in website mode, the media controller window can be closed with the X button. Then, all windows close except for the website controller window, which itself cannot be closed without getting a bunch of error messages.
Closing media controller window should be blocked while in website mode, I think.

**Comment by mtdvlpr** [comment]
@sircharlo, I agree!

**Comment by mtdvlpr** [comment]
@sircharlo, that should do the trick :)

**Comment by sircharlo** [comment]
This PR can be merged I think, unless there's something else you wanted to add for now?

**Pull request merged**
