### PR TITLE
feat: several subtitle improvements

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

- [x] ignore subs if duration off by 2s or more
- [x] show cc available and toggle specific video cc before playing video
- [x] master toggle for subs
- [x] auto detect subtitled -> move subs to top
- [x] manual override -> move subs to top 

Related to #1408 #1409 #1410 #1411

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@sircharlo, here's some work for you to test :)

**Comment by sircharlo** [comment]
> @sircharlo, here's some work for you to test :)
> 
> Any suggestions for the manual sub override action placement?

Awesome!!

Hmm. Right click on master toggle maybe? Or press and hold?

**Comment by mtdvlpr** [comment]
Hmm. How would we make either option clear to the users? I was initially thinking another button inside the video preview, but it's getting a little crowded in there...

**Comment by sircharlo** [comment]
> Hmm. How would we make either option clear to the users? I was initially thinking another button inside the video preview, but it's getting a little crowded in there...

No kidding. What if subtitle enabling/disabling was done exclusively from the top button, and subtitle position handled from the video preview?

**Comment by mtdvlpr** [comment]
@sircharlo, I would say the top button is to toggle subtitles and video preview for position, since position is always video specific and toggling subs usually stays the same across multiple videos. I'll see if I can make the button clearer to signify position change from now on.

**Comment by mtdvlpr** [comment]
@sircharlo, aright. If you click the cc button in the video preview, it will switch from being at the top right to the top left to resemble the position of the subtitles.

**Comment by sircharlo** [comment]
Do you think adding a "change subtitle position" tooltip would be beneficial, or TMI?

**Comment by sircharlo** [comment]
Also, to keep things as tidy as possible, perhaps the "toggle subtitles" button should be hidden if no subtitles are available in the media list?

**Comment by mtdvlpr** [comment]
> Do you think adding a "change subtitle position" tooltip would be beneficial, or TMI?

I tried adding it, but somethings keeping it from showing up. Give it a go if you want, but I'd declare it TMI.

**Comment by sircharlo** [comment]
> > Do you think adding a "change subtitle position" tooltip would be beneficial, or TMI?
> 
> I tried adding it, but somethings keeping it from showing up. Give it a go if you want, but I'd declare it TMI.

How's this?

**Comment by mtdvlpr** [comment]
@sircharlo, perfect! Exactly what I did, except I forgot the v-on...can I blame the late hour?😅

**Comment by mtdvlpr** [comment]
Ready for merge?

**Comment by sircharlo** [comment]
> @sircharlo, perfect! Exactly what I did, except I forgot the v-on...can I blame the late hour?😅

😂😂 I'm just happy to be able to contribute something, anything!



> Ready to merge?

I think so!

**Pull request merged**
