### PR TITLE
add malagasy to langs

### PR DESCRIPTION
**Pull request by mtdvlpr**

### CODE REVIEW

**Comment by sircharlo** [comment]
`Module not found: Error: Can't resolve 'dayjs/locale/mg' in '/home/runner/work/***/***/src/renderer/.nuxt'`

Seems like Malagasy isn't part of dayjs' list of locales...

**Comment by mtdvlpr** [comment]
> `Module not found: Error: Can't resolve 'dayjs/locale/mg' in '/home/runner/work/***/***/src/renderer/.nuxt'`
> 
> Seems like Malagasy isn't part of dayjs' list of locales...

That's unfortunate.

**Comment by mtdvlpr** [comment]
https://github.com/sircharlo/meeting-media-manager/discussions/508#discussioncomment-4069599

**Comment by sircharlo** [comment]
Oh! Didn't see you were working on that. I had started by filtering out the languages that don't have `dayjs `support from `LOCAL_LANGS `into a new const, but then I noticed that `LOCAL_LANGS `is actually only used for `dayjs`-related things. Can't we just comment out `mg` from the `LOCAL_LANGS` array?

**Comment by mtdvlpr** [comment]
> Oh! Didn't see you were working on that. I had started by filtering out the languages that don't have `dayjs` support from `LOCAL_LANGS` into a new const, but then I noticed that `LOCAL_LANGS` is actually only used for `dayjs`-related things. Can't we just comment out `mg` from the `LOCAL_LANGS` array?

That's indeed a better idea. Just comment it out until it's supported.

**Pull request merged**
