### PR TITLE
feat: add announcement for obs breaking change

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

-
-
-

Related to #3668

### CODE REVIEW

**Comment by sircharlo** [comment]
I'd feel more comfortable if we reverted the OBS change, showed the banner, and said that it will be as of v25.1.0. That way, sysadmins have time to prepare for the change.

**Comment by mtdvlpr** [comment]
> I'd feel more comfortable if we reverted the OBS change, showed the banner, and said that it will be as of v25.1.0. That way, sysadmins have time to prepare for the change.

Done :)

**Comment by mtdvlpr** [comment]
I think after this we're ready to release another version and close 27 issues 🚀

**Comment by sircharlo** [comment]
Awesome!

**Pull request merged**
