### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by wifilogo**
add installNow locale

### CODE REVIEW

**Comment by mtdvlpr** [comment]
Thank you for your contribution! Would you be interested in being an official moderator for Spanish? I can add you to the gitLocalize repo which will simplify the translation process for you.

**Comment by mtdvlpr** [comment]
There seems to be a problem with your es.json file, so I copied your strings and made another PR (see #550)

**Comment by wifilogo** [comment]
> @wifilogo, thank you for your contribution! Would you be interested in being an official moderator for Spanish? I can add you to the gitLocalize repo which will simplify the translation process for you.

Okay.
I'm not familiar with Github but I'll try.
Thanks.

**Comment by mtdvlpr** [comment]
Thank you so much!

To get started, please [sign into GitLocalize](https://gitlocalize.com/) using your GitHub account, and then let me know when that's done by adding a comment in this chat. 

As language moderator, you will get notified of changes to the English original strings, have a nice and easy to use interface to review existing as well as untranslated strings in your language, and submit new translations to the repo easily.

**Comment by wifilogo** [comment]
> Thank you so much!
> 
> To get started, please [sign into GitLocalize](https://gitlocalize.com/) using your GitHub account, and then let me know when that's done by adding a comment in this chat.
> 
> As language moderator, you will get notified of changes to the English original strings, have a nice and easy to use interface to review existing as well as untranslated strings in your language, and submit new translations to the repo easily.

I'm already signed in to GitLocalize with my GitHub account.

**Comment by mtdvlpr** [comment]
@wifilogo, great! I have added you to the gitLocalize repo. Thank you for your willing spirit!

**Comment by wifilogo** [comment]
I see.
Thank you :)

**Pull request closed without merging**
