### PR TITLE
feat(jwpub): display missing media

### PR DESCRIPTION
**Pull request by sircharlo**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

-
-
-

Related to #3427

### CODE REVIEW

**Comment by ux-git** [comment]
@sircharlo do you need any design input for the missing media placeholders or something else? Or if you want, you can do it like you wish and then share the screenshots, and I'll share my quick feedback and perhaps some visual suggestions if applicable.

**Comment by sircharlo** [comment]
> @sircharlo do you need any design input for the missing media placeholders or something else? Or if you want, you can do it like you wish and then share the screenshots, and I'll share my quick feedback and perhaps some visual suggestions if applicable.

I'll never say no to feedback! Want screenshots or a test build?

**Comment by ux-git** [comment]
For now screenshots would be better because I'm always keep rushing here and there :)

**Comment by ux-git** [comment]
When thinking about intuitiveness, I have the following approach on my mind:

1. All the controls and title are grey highlighting that they're just inactive. Not red as an error or mistake, but rather inactivity.
2. The preview image is pretty much faded out, to emphasize that the media is not actually there there (thats the point that is currently very unclear in the Library, user has to first click to learn that the video is actually unavailable).
3. The explainer text in written just below the image description/name. Reasons: a) we have a lot of space there, b) it's immediately accessible and explains what to do, no need to search for the hover hint (otherwise user must also come up with an idea to hover over the icon first).
4. In the middle of the thumbnail we can place the "Import first" text with an icon to make it even more clear what to do. By clicking on it the import window can open right away. This is to make it 100% obvious, but I do also like the layout without this button on top because it looks way less busy this way (second attachment).

Screenshot 2024-11-20 at 23 40 33

– or –
Screenshot 2024-11-20 at 23 40 53

**Comment by sircharlo** [comment]
I like it! So no more orange banner on top?

1. Done
2. Done
3. Done
4. I like the second option personally.

image

**Comment by mtdvlpr** [comment]
This is very nice! A little off topic tip: when this is ready to be merged, try `Squash and merge` instead of `Create a merge commit`. This will bundle all the commits of the PR into one commit where the commit message is the PR title. This helps in keeping the master branch commit history clean and therefore also helps in creating the changelog for the next version. This also means you can be as brief or unclear as you want when committing to this branch, since the end result will be one clearly described commit anyway.

**Comment by ux-git** [comment]
Looks good! 

> I like it! So no more orange banner on top?

Maybe it would be better to display a temp error message but orange instead of red, to attract the attention for a short time, shortly explain that "_The file was imported successfully. However, some files are included as placeholders because their media is not directly provided in the import file. You can add the media manually if needed_".

This way the attention will be pointed, quickly informed about the issue and all the further instructions are directly on the media items.

**Comment by ux-git** [comment]
Also, another idea about the custom media badge:

We could integrate the star into the label itself, placing it alongside indicators like "Song," "Footnote," and "Paragraph." This would make the badge’s location predictable and consistent, ensuring users always know where to look for this information. The only clear downside I can see is that we can't add a text like "Custom" there because the label will be too long (and with some translations way longer). Normally we use short numbers or paragraph set of 2 or 3 parapgraphs, that's why any word longer than 5 letters is too long, so perhaps replacing the text with a hover tooltip would do the trick. Your thoughts? 

Screenshot 2024-11-21 at 09 04 33

Alternatively, we could remove the stars entirely, not just for the "Other" congregation type but for the entire "Extra Media" section. Since all media in this section is custom, the stars might be redundant.

To conclude, I think moving the star to the label on the left would be the better solution. It provides clarity while beeing consistent and avoids spreading out the indicators across the interface.

**Comment by ux-git** [comment]
Some other options instead of the start icon, since it's relatively easy to mix it up with the footnote icon. Let me know @sircharlo @mtdvlpr what would you prefer. 

Screenshot 2024-11-21 at 09 40 15

**Comment by ux-git** [comment]
Aaand (sorry 😄) giving it a fresh look today I guess the white overlay can be somewhere around 64% opacity, to make the image a bit better visible (especially when there are multiple in the row, to better distinguish them), but still obvious that it's unavailable.

**Comment by ux-git** [comment]
@mtdvlpr agree, not bad

Screenshot 2024-11-21 at 09 51 25

**Comment by mtdvlpr** [comment]
Let's continue the extra media indicator conversation to #3452

**Comment by sircharlo** [comment]
image

With the latest feedback. Any other suggested changes? 😄

**Comment by mtdvlpr** [comment]
What looks better, the red badge or if the badge matches the banner color?

image

**Comment by ux-git** [comment]
@mtdvlpr I find the red one better

**Pull request merged**
