### PR TITLE
feat: improve custom start/stop time experience

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Proposed Changes

A clear and concise description of the changes in this pull request.

If applicable, list the changes in a list:

- 
- 
- 

Related to #1469

### CODE REVIEW

**Comment by mtdvlpr** [comment]
@stepstra, could you please [test this version](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9?usp=sharing) for me and let me know what you think of the renewed inputs?

**Comment by stepstra** [comment]
Input is now OK. For me, the numbers needn't be so big but that's a matter of taste.
But the confirmation button still looks like a checkbox to me. But least the tooltip shows what it does, that's ok.
image

**Comment by sircharlo** [comment]
> Input is now OK. For me, the numbers needn't be so big but that's a matter of taste. But the confirmation button still looks like a checkbox to me. But least the tooltip shows what it does, that's ok. image

Don'T tell me you want a floppy disk icon! 😆

**Comment by stepstra** [comment]
> 
> Don't tell me you want a floppy disk icon! 😆 

There's an idea! 👍😅

**Pull request merged**
